import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import DaisyUiThemeProvider from "@/providers/DaisyUiThemeProvider";
import SessionHandler from "@/components/common/Signup/SessionHandler";
import "animate.css";
import GoogleOAuth from "@/providers/GoogleOAuth";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <DaisyUiThemeProvider>
            <GoogleOAuth>
            <SessionHandler />   {/* automatic logoout if the firebase token expires */}
               <ToastContainer position="top-right" autoClose={3000} />
            {children}
            </GoogleOAuth>
          </DaisyUiThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
