import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import DaisyUiThemeProvider from "@/providers/DaisyUiThemeProvider";
import AuthListener from "@/components/common/Signup/AuthListner";
import "animate.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
  <ReduxProvider>
    <DaisyUiThemeProvider>
      <AuthListener/>      {/* automatic logoout if the firebase token expires */}
          {children}
          </DaisyUiThemeProvider>
   </ReduxProvider>
      </body>
    </html>
  );
}
